# You should always specify a full version here to ensure all of your developers
# are running the same version of Node.
FROM node:8 as build
WORKDIR /app

COPY . .
RUN yarn install

# Build Everything
RUN yarn build

# Install `serve` to run the application.
RUN npm install -g serve@7.2.0

# Set the command to start the node server.
CMD yarn serve:dapp

# Tell Docker about the port we'll run on.
EXPOSE 3000
