export enum PHASE_TYPE_NAMES {
  IN_APPLICATION = "IN_APPLICATION",
  CHALLENGE_COMMIT_VOTE = "CHALLENGE_COMMIT_VOTE",
  CHALLENGE_REVEAL_VOTE = "CHALLENGE_REVEAL_VOTE",
}

export enum PHASE_TYPE_LABEL {
  IN_APPLICATION = "Awaiting Approval",
  CHALLENGE_COMMIT_VOTE = "Under Challenge",
  CHALLENGE_REVEAL_VOTE = "Under Challenge",
}

