export enum IncomingMessageType {
  GET_STATUS = "GET_STATUS",
  CREATE_KEY = "CREATE_KEY",
  GET_KEY = "GET_KEY",
  GENERATE_KEY = "GENERATE_KEY",
  SEND_DEVICE_ACTIVATION_REQUEST = "SEND_DEVICE_ACTIVATION_REQUEST",
  CONFIRM_DEVICE_ACTIVATION_REQUEST = "CONFIRM_DEVICE_ACTIVATION_REQUEST",
}
